site_name: MAD1
nav:
- Home:
  - index.md
  - Flask.md
  - css.md
- week3:
  - week3/Week 3_annotated.md
  - week3/Accessibilty.md
  - week3/heuristics.md
- week1:
  - week1/pq_session.md
  - week1/Week 1_annotated.md
  - week1/week_activity1.md
- arifacts:
  - arifacts/1.md
  - arifacts/viva.md
- week2:
  - week2/Week 2_annotated.md
- reference:
  - reference/embeding.md
site_author: PK
site_description: DESCRIPTION
repo_name: pk1308/MAD1
repo_url: https://github.com/pk1308/MAD1
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/pk1308
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- pymdownx.pathconverter
plugins:
- search
- mkdocs-pdf
copyright: '&copy; 2024 <a href="https://github.com/pk1308"  target="_blank" rel="noopener">PK</a>'
