site_name: MAD1
nav:
- Home:
  - css.md
  - Flask.md
  - index.md
- arifacts:
  - arifacts/1.md
  - arifacts/viva.md
- reference:
  - reference/embeding.md
- Week 11:
  - Week 11/Week 11 [1-13].md
  - Week 11/Week 11 [14-23].md
  - Week 11/Week 11 [24-28].md
- Week 12:
  - Week 12/Week 12 [1-20].md
  - Week 12/Week 12 [21-29].md
  - Week 12/Week 12 [30-43].md
- week 5:
  - week 5/crud.md
  - week 5/mvc.md
  - week 5/route.md
- Week 6:
  - Week 6/apidesign.md
  - Week 6/json.md
  - Week 6/openapi.md
  - Week 6/Rest_lec6_2.md
  - Week 6/Week 6-53-70.md
- week1:
  - week1/pq_session.md
  - week1/Week 1_annotated.md
  - week1/week_activity1.md
- week10:
  - week10/Week 10 [1-16].md
  - week10/Week 10 [17-31].md
  - week10/Week 10 [32-42].md
  - week10/Week 10 [43-60].md
- week2:
  - week2/activity_session_.md
  - week2/aq_pq.md
  - week2/Week 2_annotated.md
- week3:
  - week3/Accessibility.md
  - week3/heuristics.md
  - week3/Week 3_annotated.md
- week4:
  - week4/Mechanisms for Persistent Storage and Relational Databases.md
  - week4/Presistent Storage.md
  - week4/Relations and ER Diagram.md
  - week4/sql.md
- week7:
  - week7/Backend Systems.md
  - week7/cors.md
  - week7/Data Search.md
  - week7/Database Search.md
  - week7/Scaling Strategies.md
  - week7/SQL vs. NoSQL.md
  - week7/WebApplicationSecurity.md
- Week8:
  - Week8/Frontends.md
  - Week8/Week 8-14-21.md
  - Week8/Week 8-22-34.md
  - Week8/Week 8-35-48.md
- week9:
  - week9/Security Mechanisms.md
  - week9/Security.md
  - week9/Week 9-1-22.md
  - week9/Week 9-23-37.md
  - week9/Week 9-38-48.md
  - week9/Week 9-49-57.md
  - week9/Week 9-58-66.md
site_author: PK
site_description: DESCRIPTION
repo_name: pk1308/MAD1
repo_url: https://github.com/pk1308/MAD1
theme:
  name: dracula
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/pk1308
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- pymdownx.pathconverter
plugins:
- search
- mkdocs-pdf
copyright: '&copy; 2024 <a href="https://github.com/pk1308"  target="_blank" rel="noopener">PK</a>'
